# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='im.proto',
  package='im',
  syntax='proto3',
  serialized_pb=_b('\n\x08im.proto\x12\x02im\"\'\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0bscreen_name\x18\x02 \x01(\t\"\x1b\n\x08MetaData\x12\x0f\n\x07latency\x18\x01 \x01(\x02\"\xd5\x01\n\x0eInstantMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1a\n\x06\x63lient\x18\x02 \x01(\x0e\x32\n.im.Client\x12\x11\n\tsender_ip\x18\x03 \x01(\x07\x12\x18\n\x06sender\x18\x04 \x01(\x0b\x32\x08.im.User\x12\x1b\n\trecipient\x18\x05 \x01(\x0b\x32\x08.im.User\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x19\n\x11image_attachments\x18\x07 \x03(\x0c\x12\x1e\n\x08metadata\x18\x08 \x01(\x0b\x32\x0c.im.MetaData*W\n\x06\x43lient\x12\x12\n\x0e\x43LIENT_UNKNOWN\x10\x00\x12\x15\n\x11\x43LIENT_NATIVE_APP\x10\x01\x12\x12\n\x0e\x43LIENT_WEB_APP\x10\x02\x12\x0e\n\nCLIENT_API\x10\x03\x62\x06proto3')
)

_CLIENT = _descriptor.EnumDescriptor(
  name='Client',
  full_name='im.Client',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_NATIVE_APP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_WEB_APP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_API', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=302,
  serialized_end=389,
)
_sym_db.RegisterEnumDescriptor(_CLIENT)

Client = enum_type_wrapper.EnumTypeWrapper(_CLIENT)
CLIENT_UNKNOWN = 0
CLIENT_NATIVE_APP = 1
CLIENT_WEB_APP = 2
CLIENT_API = 3



_USER = _descriptor.Descriptor(
  name='User',
  full_name='im.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='im.User.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='screen_name', full_name='im.User.screen_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=55,
)


_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='im.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latency', full_name='im.MetaData.latency', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=84,
)


_INSTANTMESSAGE = _descriptor.Descriptor(
  name='InstantMessage',
  full_name='im.InstantMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='im.InstantMessage.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client', full_name='im.InstantMessage.client', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender_ip', full_name='im.InstantMessage.sender_ip', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='im.InstantMessage.sender', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recipient', full_name='im.InstantMessage.recipient', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='im.InstantMessage.message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_attachments', full_name='im.InstantMessage.image_attachments', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='im.InstantMessage.metadata', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=300,
)

_INSTANTMESSAGE.fields_by_name['client'].enum_type = _CLIENT
_INSTANTMESSAGE.fields_by_name['sender'].message_type = _USER
_INSTANTMESSAGE.fields_by_name['recipient'].message_type = _USER
_INSTANTMESSAGE.fields_by_name['metadata'].message_type = _METADATA
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.message_types_by_name['InstantMessage'] = _INSTANTMESSAGE
DESCRIPTOR.enum_types_by_name['Client'] = _CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'im_pb2'
  # @@protoc_insertion_point(class_scope:im.User)
  ))
_sym_db.RegisterMessage(User)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'im_pb2'
  # @@protoc_insertion_point(class_scope:im.MetaData)
  ))
_sym_db.RegisterMessage(MetaData)

InstantMessage = _reflection.GeneratedProtocolMessageType('InstantMessage', (_message.Message,), dict(
  DESCRIPTOR = _INSTANTMESSAGE,
  __module__ = 'im_pb2'
  # @@protoc_insertion_point(class_scope:im.InstantMessage)
  ))
_sym_db.RegisterMessage(InstantMessage)


# @@protoc_insertion_point(module_scope)