# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loop.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nloop.proto\"\x1b\n\x04Loop\x12\x13\n\x04loop\x18\x01 \x01(\x0b\x32\x05.Loopb\x06proto3')
)




_LOOP = _descriptor.Descriptor(
  name='Loop',
  full_name='Loop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loop', full_name='Loop.loop', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=41,
)

_LOOP.fields_by_name['loop'].message_type = _LOOP
DESCRIPTOR.message_types_by_name['Loop'] = _LOOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Loop = _reflection.GeneratedProtocolMessageType('Loop', (_message.Message,), dict(
  DESCRIPTOR = _LOOP,
  __module__ = 'loop_pb2'
  # @@protoc_insertion_point(class_scope:Loop)
  ))
_sym_db.RegisterMessage(Loop)


# @@protoc_insertion_point(module_scope)
